title: Colin Grimm # your name (or website title) here
logo: "images/CompositePicture.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/feed/?trk=onboarding-landing">LinkedIn</a> 
  <br>
  <a href="Colin Resume PDF.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/colingrimm/">GitHub</a>  
 
  
theme: jekyll-theme-minimal
